/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bin.MetadataParser;
import java.io.File;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableModel;
import utiility.AccionesVentana;
import utiility.JFolderChooser;

/**
 *
 * @author hangarita
 */
public class Index extends javax.swing.JFrame {

    AccionesVentana nuevo;
    String strRoot = System.getProperty("user.dir");
    JFolderChooser chooser;
    ArrayList<String> fileList;

    /**
     * Creates new form Index
     */
    public Index() {
        AccionesVentana.LooknFeel();
        initComponents();
        nuevo = new AccionesVentana(this, "XML Data Generator");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFolder = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        txtFolderProyect = new javax.swing.JTextField();
        btnRead = new javax.swing.JButton();
        pnlData = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        btnFix = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        pnlFolder1 = new javax.swing.JPanel();
        btnSearchXML = new javax.swing.JButton();
        txtXMLFile = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlFolder.setBorder(javax.swing.BorderFactory.createTitledBorder("Object Folder"));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtFolderProyect.setEditable(false);
        txtFolderProyect.setBackground(new java.awt.Color(255, 255, 255));
        txtFolderProyect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFolderProyectActionPerformed(evt);
            }
        });

        btnRead.setText("Read");
        btnRead.setEnabled(false);
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFolderLayout = new javax.swing.GroupLayout(pnlFolder);
        pnlFolder.setLayout(pnlFolderLayout);
        pnlFolderLayout.setHorizontalGroup(
            pnlFolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFolderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFolderProyect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRead)
                .addContainerGap())
        );
        pnlFolderLayout.setVerticalGroup(
            pnlFolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFolderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(txtFolderProyect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRead))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "FILES"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pnlData.setViewportView(tblData);
        if (tblData.getColumnModel().getColumnCount() > 0) {
            tblData.getColumnModel().getColumn(0).setResizable(false);
        }

        btnFix.setText("Fix!");
        btnFix.setEnabled(false);
        btnFix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFixActionPerformed(evt);
            }
        });

        lblMessage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(255, 0, 0));

        pnlFolder1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)), "XML Data Lesson"));

        btnSearchXML.setText("Search");
        btnSearchXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchXMLActionPerformed(evt);
            }
        });

        txtXMLFile.setEditable(false);
        txtXMLFile.setBackground(new java.awt.Color(255, 255, 255));
        txtXMLFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtXMLFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFolder1Layout = new javax.swing.GroupLayout(pnlFolder1);
        pnlFolder1.setLayout(pnlFolder1Layout);
        pnlFolder1Layout.setHorizontalGroup(
            pnlFolder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFolder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSearchXML)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtXMLFile)
                .addContainerGap())
        );
        pnlFolder1Layout.setVerticalGroup(
            pnlFolder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFolder1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFolder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchXML)
                    .addComponent(txtXMLFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlFolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFolder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFix))
                            .addComponent(pnlData, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFolder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlData, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchingFolder() {
        try {

            txtFolderProyect.setText(chooser.getStrPath());
            btnRead.setEnabled(true);
        } catch (Exception ex) {
            btnRead.setEnabled(false);
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        chooser = new JFolderChooser();
        chooser.OpenChooser("");
        SearchingFolder();

    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtFolderProyectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFolderProyectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFolderProyectActionPerformed

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        fileList = chooser.getFileList();

        TableModel model = tblData.getModel();

        Iterator<String> ite = fileList.iterator();
        int cont = 0;

        while (ite.hasNext()) {
            String ele = ite.next();

            model.setValueAt(ele, cont, 0);

            cont++;
        }

        pnlFolder.setEnabled(false);
        btnRead.setEnabled(false);
        btnSearch.setEnabled(false);

        btnFix.setEnabled(true);

    }//GEN-LAST:event_btnReadActionPerformed

    private void btnFixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFixActionPerformed
        btnSearchXML.setEnabled(false);
        String[] arrData = {txtFolderProyect.getText(), txtXMLFile.getText()};
        lblMessage.setText("Trabajando...");
        MetadataParser.main(arrData);

    }//GEN-LAST:event_btnFixActionPerformed

    private void btnSearchXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchXMLActionPerformed
        JFileChooser jchus = new JFileChooser();
        jchus.setCurrentDirectory(new java.io.File("."));
        jchus.setFileFilter(new FileNameExtensionFilter("metadata.xml", "xml"));
        jchus.showDialog(this, null);
        try {
            txtXMLFile.setText(jchus.getSelectedFile().getAbsolutePath());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSearchXMLActionPerformed

    private void txtXMLFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtXMLFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtXMLFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFix;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchXML;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JScrollPane pnlData;
    private javax.swing.JPanel pnlFolder;
    private javax.swing.JPanel pnlFolder1;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtFolderProyect;
    private javax.swing.JTextField txtXMLFile;
    // End of variables declaration//GEN-END:variables
}
